# Generated by Django 5.1.7 on 2025-03-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clint',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clint',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clint',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clint',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clint',
            name='tall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clint',
            name='wight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
