# Generated by Django 5.1.4 on 2025-03-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_clint_category_alter_clint_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='clint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
